### ISSUE TITLE
Single letter after hyphen in local-part evals false

### ISSUE THREAD

**Issue by jamesholcomb** [niftylettuce/email-regex-safe#1]
```js
const emailRegEx = require('email-regex-safe');
const validator = require('validator');

console.log(validator.isEmail('bill-g@ms.com'));  // true
console.log(emailRegEx().test('email me bill-g@ms.com'));  // false
console.log(emailRegEx().test('email me bill-gates@ms.com'));  // true
```

Thanks for putting together this repo.

**Comment by niftylettuce** [comment]
Any chance you could submit a PR to fix with a test?

**Comment by jamesholcomb** [comment]
How did you come up with the local-part regex?

https://github.com/niftylettuce/email-regex-safe/blob/0ef7567ec8c5b9db0c6a742920e8d9a21a502c5e/src/index.js#L44

**Comment by shadowgate15** [comment]
@jamesholcomb this actually isn't a bug.

You need to add `gmail: false` to options for `emailRegexSafe`. The local part is not a valid gmail local part but otherwise it is.
