### ISSUE TITLE
[bug] Emails with capital letters invalid when config has `gmail: false`

### ISSUE THREAD

**Issue by mattwelke** [niftylettuce/email-regex-safe#5]
## Describe the bug

**Node.js version:**
Node.js 18

**OS version:** Ubuntu 22.04

**Description:**

When changing the Gmail mode from its default `true` to `false`, the regex produced considers email addresses with capital letters invalid. I think email addresses that have capital letters are valid because apparently modern email servers ignore case.

Can you clarify? Is this a bug or intended behavior? If intended, why?

## Actual behavior

Regex produced with `gmail: false` in config considers emails invalid if they have a capital letter.

## Expected behavior

Regex produced with `gmail: false` in config does not consider emails invalid if they have a capital letter.

## Code to reproduce

Use this code to get the regex:

```js
const emailRegexSafe = require('email-regex-safe');
const regexString = emailRegexSafe({
    exact: true,
    returnString: true,
    gmail: false,
});
```

(can console log it etc)

Or, check out the latest commit in the branch in the repo for an open source lib I maintain at https://github.com/schema-inspector/schema-inspector/pull/143. One of our unit tests is failing with candidate "nikitaJS@pantera.com" when I change to the new regex.

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by titanism** [comment]
This would be a bug - PR is welcome to fix.  Typically though we would `toLowerCase()` before running against this.

**Comment by mattwelke** [comment]
@titanism Would lowercasing input before validating using this be a good workaround? In the library I maintain, we could do this as a workaround, if I struggle to get a PR in here.

**Comment by titanism** [comment]
Yes that's what we do
