### ISSUE TITLE
Let a user decide to use or not to use re2

### ISSUE THREAD

**Issue by houd1ni** [niftylettuce/email-regex-safe#6]
Hello! i've been using this in frontend projects and now have to pick a similar thing in some micro node server with very limited memory. The build suddenly fails, making me make some additional research that ended in rereading docs of this lib, - good, the disclaimer about RE2 is in top 👍  The RE2 dep is large, native and unwanted dependency for my use case, but email-regex-safe itself is completely perfect.

And what if I decide to use Google's PCRE fork ?

Maybe make an `engine` option ? Like this `emailRegex({exact: true, engine: re2})`.

Off-topic: Why did the author of RE2 write another library, but not a PR with super-duper important security features into Node? Are users of native Node RegExp all in endless restart loop ? c:

**Comment by titanism** [comment]
PR welcome as long as its backwards compatible - though we don't see any PCRE forks on npm?  RE2 is a PCRE alternative.  Yes, Node's regex is vulnerable and not many developers are aware that [ReDoS](https://en.wikipedia.org/wiki/ReDoS) even exist.

**Comment by houd1ni** [comment]
https://github.com/google/re2 yeah it's not in npm, but nothing prevents anyone to make an addon-wrapper around and attach to email-safe-regex in that case if needed.

I believe ReDoS is a regex provider work, not an engine, just like any code itself. What RE2 do in the case of "bad regex" or "evil input"? I really cannot see nothing special in its' docs and its' links to "check you regex' are broken.

The completely backwards compatible PR is not possible since there're only two initial options:

- Remove the dep, but require node users to explicitly provide a regex engine into the options, leave hints in the docs.
- Default to native RegExp (I guess, no).
- Leave the dep and let a user choose. This case does not satisfy my needs though.

Is 3.0.0 an option ?

**Comment by titanism** [comment]
Yea, sorry about that - 3.0.0 is ok!  Just don't bump the version in the PR, we do that via `np`.

**Comment by titanism** [comment]
v3.0.0 is released with optional `re2` support, thank you @analog-nico 

https://github.com/spamscanner/email-regex-safe/releases/tag/v3.0.0
